name: Octane Ticket Creator

on:
  issue_comment:
    types: [created, edited]

jobs:
  issue_comment:
    name: Issue comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: jamesnswithers/octane-story-creator-action@main
        with:
          SERVER: '${{ secrects.OCTANE_SERVER }}'
          WORKSPACE: '${{ secrects.OCTANE_WORKSPACE }}'
          SHARED_SPACE: '${{ secrects.OCTANE_SHAREDSPACE }}'
          USER: '${{ secrects.OCTANE_USER }}'
          PASSWORD: '${{ secrects.OCTANE_PASSWORD }}'