name: Update Pull Requests

on:
  push:
    branches:
      - release-*
      - main

jobs:
  update_pull_requests:
    runs-on: ubuntu-latest
    steps:
      - name: Update Pull Requests
        run: |
          pulls=`gh pr list --json number,title,baseRefName --base ${{ github.ref_name }} --label "auto-update" --state open --repo ${{ github.repository }}`
          echo "$pulls"
          d=`date '+%FT+%TZ'`
          echo "$d"
          for pull in $(echo '$pulls' | jq '.[]'); do
            base_ref=`echo "$pull" | jq '.baseRefName'
            head_sha=`gh api '/repos/jamesnswithers/test-repository/commits?sha=$base_ref&until='$d'&per_page=1&page=1' | jq '.[].sha'`
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
