name: Update Pull Requests

on:
  push:
    branches:
      - release-*
      - main

jobs:
  update_pull_requests:
    runs-on: ubuntu-latest
    steps:
      - name: Update Pull Requests
        run: |
          pulls=`gh pr list --json number,title,headRefName --base ${{ github.ref_name }} --label "auto-update" --state open --repo ${{ github.repository }}`
          echo "$pulls"
          d=`date '+%FT+%TZ'`
          echo "$d"
          for pull in $(echo "${pulls}" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${pull} | base64 --decode | jq -r ${1}
            }
            base_ref=`echo $(_jq '.headRefName')`
            echo "$base_ref"
            echo '/repos/jamesnswithers/test-repository/commits?sha='$base_ref'&until='$d'&per_page=1&page=1'
            head_sha=`gh api '/repos/jamesnswithers/test-repository/commits?sha='$base_ref'&until='$d'&per_page=1&page=1' | jq '.[].sha'`
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
