name: Release Draft PR Creator

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
      - development
      - release-*

jobs:
  create_draft_pr:
    name: Release Draft PR Creator
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Check existing PRs
        run: gh pr list --repo ${{ github.repository }} --draft --state open
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Auth Status
        run: gh auth status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Shallow Clone of Repo      
        run: |
          git remote add origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          gh repo clone {{ github.repository -- --sparse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: true
