name: Release Draft PR Creator

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
      - development
      - release-*

jobs:
  create_draft_pr:
    name: Release Draft PR Creator
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Shallow Clone of Repo      
        run: |
          git clone --sparse https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: true

      - name: Debug
        run: |
          dir
          ls
          pwd
          gh auth status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check existing PRs
        run: gh pr list --draft --state open
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
