name: Release Draft PR Creator

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
      - development
      - release-*

jobs:
  create_draft_pr:
    name: Release Draft PR Creator
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Check existing PRs
        run: gh pr list --repo "${{ github.repository }}" --draft --state open
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Shallow Clone of Repo
        run: gh repo clone "git@github.com:${{ github.repository }}.git" -- --sparse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
