name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - release-*
  pull_request:
    branches:
      - development
      - main
    types: ['opened', 'edited', 'reopened', 'ready_for_review']

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
        
      - id: set_vars
        run: |
          content=`cat ./.github/branchInfo.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=branch_json::$content"
          echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
      
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@242921599b8dec2acb4a3e87d9c2d56d502b6712
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          disable-releaser: ${{ github.ref != 'refs/heads/main' }}
          disable-autolabeler: ${{ github.ref == 'refs/heads/main' }}
          commitish: ${{ steps.set_vars.outputs.branch }}
          name: ${{ fromJson(steps.set_vars.outputs.branch_json)[steps.set_vars.outputs.branch].releaseName }}
          version: ${{ fromJson(steps.set_vars.outputs.branch_json)[steps.set_vars.outputs.branch].releaseName }}
          tag: ${{ fromJson(steps.set_vars.outputs.branch_json)[steps.set_vars.outputs.branch].releaseName }}
